### ISSUE TITLE
Installation error caused by yaml-cpp

### ISSUE THREAD

**Issue by TheFrey222** [uzh-rpg/rpg_svo_pro_open#41]
Was not able to build everything, since the yaml-cpp files weren't compatible. Example error message:

`undefined reference to YAML::detail::`

The solution was to downgrade the yaml installation. The working version was "yaml-cpp-0.6.0" 
With that version, everything compiled fine

**Comment by hamdaan19** [comment]
Hi @TheFrey222

I am facing the same problem. Can you please tell me how you downgraded yaml-cpp ? Did you git clone the yaml-cpp repo with the correct version and do `sudo make install`. Or is there any other procedure? Would be of great help if you could reply. Thanks.

**Comment by TheFrey222** [comment]
Hi @hamdaan19 

Yes, I just changed to the "yaml-cpp-0.6.0"-tagged branch and installed it exactly as stated in the "install.txt" file

**Comment by hamdaan19** [comment]
Thanks for lightning-speed reply @TheFrey222. Much appreciated! :) 

I did exactly as you said in your comment above. I am still facing the same problem. I do have libyaml-cpp-dev installed via the apt package manager. Should I uninstall it and try again? Or is there a way I can specify a path in any of the CMake files to find the package with the correct version?

**Comment by TheFrey222** [comment]
You are welcome.

I would uninstall all other yaml-cpp packages you have installed and try again. I would not mess too much with the CMake files if you don't have to.

**Comment by hamdaan19** [comment]
> Hi @hamdaan19
> 
> Yes, I just changed to the "yaml-cpp-0.6.0"-tagged branch and installed it exactly as stated in the "install.txt" file

I followed the steps you mentioned and then cleaned the catkin workspace and rebuilt it. This fixed the issue. 
```
catkin clean --all
catkin build --force-cmake
```

Thanks for the help! @TheFrey222
