### ISSUE TITLE
Can it run without ROS?

### ISSUE THREAD

**Issue by manojsharma221** [uzh-rpg/rpg_svo_pro_open#6]
Any tips on how to run it without ROS? Say on Windows?

**Comment by manojsharma221** [comment]
I can run without ROS. Closing the issue as I have figured it out.

**Comment by TimeEscaper** [comment]
> I can run without ROS. Closing the issue as I have figured it out.

Sorry for re-opening the issue, but still: what exactly did you mean under running without ROS? Did you manage to run SVO on data not in the format of rosbags, but in some other format? Because we have similar issue because of having our trajectories in the EuRoC ASL format, not in the rosbags.

**Comment by anchuanxu** [comment]
> I can run without ROS. Closing the issue as I have figured it out.

Hello, I also want to run without relying on ROS, how did you do it? Is there a brief tutorial? thanks.
